In [30]:
#Importing the Essential Libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [31]:
#loading the Iris Dataset
iris=load_iris()

In [32]:
#Checking the Feature And Target names
print("Feature Names Are")
print(iris.feature_names)

print("Target Categories  Are")
print(iris.target_names)

Feature Names Are
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target Categories  Are
['setosa' 'versicolor' 'virginica']


In [33]:
#Assigning the Dependent and independent variables
Indep_var=iris.data
Dep_var=iris.target

In [34]:
#Splitting the Dataset into training and testing with train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(Indep_var,Dep_var,test_size=0.25,random_state=4)

In [35]:
#Checking the splitted classes
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(112, 4)
(38, 4)
(112,)
(38,)


In [36]:
#Creating the Instance of KNN class and fitting the Data
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [37]:
Y_pred_test=knn.predict(X_test)

In [38]:
Y_pred_test

array([2, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 1, 2, 0, 1, 0, 0, 2, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 2, 0, 1, 2, 2, 1])

In [39]:
#Computing the Accuracy
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

results = confusion_matrix(Y_test, Y_pred_test) 
print('Confusion Matrix :')
print(np.array(results)) 
print ('Accuracy Score :',accuracy_score(Y_test, Y_pred_test) )
print( 'Report : ')
print( classification_report(Y_test, Y_pred_test) )

Confusion Matrix :
[[18  0  0]
 [ 0  7  1]
 [ 0  0 12]]
Accuracy Score : 0.9736842105263158
Report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      0.88      0.93         8
           2       0.92      1.00      0.96        12

    accuracy                           0.97        38
   macro avg       0.97      0.96      0.96        38
weighted avg       0.98      0.97      0.97        38



Confusion Matrix :
[[18  0  0]
 [ 0  7  1]
 [ 0  0 12]]
Accuracy Score : 0.9736842105263158
Report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      0.88      0.93         8
           2       0.92      1.00      0.96        12

    accuracy                           0.97        38
   macro avg       0.97      0.96      0.96        38
weighted avg       0.98      0.97      0.97        38

